site_name: Batchly Support
pages: 
- Home : 'index.md'
- About : 
    - 'Why Batchly' : 'about/whybatchly.md'
- User Guide:
    - 'Getting Started': 'user-guide/getting-started.md'
    - 'User Management': 'user-guide/user-management.md'
- IAM Access:
    - 'Create IAM Access': 'iam-access/iam-access.md'
- Apps:
    - 'JMeter': 'jmeter/jmeter.md'
    - 'FFmpeg': 'ffmpeg/ffmpeg.md'
    - 'ImageMagick': 'imagemagick/imagemagick.md'
    - 'Big Data Apps': 'bigdata/spark.md'
- API:
    - 'API Overview': 'api/overview.md'
    - 'Definition': 'api/definition.md'
    - 'App Specific APIs': 'api/app-api.md'
theme: cinder