site_name: Batchly Support
pages: 
- Home : 'index.md'
- About : 
    - 'Why Batchly' : 'whybatchly.md'
- User Guide:
    - 'Getting Started': 'user-guide/getting-started.md'
    - 'User Management': 'user-guide/user-management.md'
    - 'Create IAM Access': 'user-guide/iam-access.md'
- Apps:
    - 'Big Data Apps': 'app-pages/spark.md'
    - 'JMeter': 'app-pages/jmeter.md'
    - 'FFmpeg': 'app-pages/ffmpeg.md'
    - 'ImageMagick': 'app-pages/imagemagick.md'
    - 'Auto Scaling': 'app-pages/autoscaling.md'
    - 'Elastic Bean Stalk': 'app-pages/beanstalk.md'
- API:
    - 'API Overview': 'api/overview.md'
    - 'Definition': 'api/definition.md'
    - 'App Specific APIs': 'api/app-api.md'
- Media API:
    - 'Media API Definition': 'media-api/media-definition.md'
    - 'Media Operations': 'media-api/media-operations.md'
    - 'Media Status Codes': 'media-api/media-codes.md'
theme: cinder